base_images:
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
  observability-operator-test-harness:
    name: observability-operator-test-harness
    namespace: ci
    tag: latest
  upi-installer:
    name: "4.18"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.22-openshift-4.17
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.18"
resources:
  '*':
    limits:
      memory: 4G
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: stage
  cron: 0 6 1 6 *
  steps:
    cluster_profile: gcp-qe
    env:
      COO_INDEX_IMAGE: brew.registry.redhat.io/rh-osbs/iib@sha256:8243f3471e7292fdde2bbb043475662b3385f7a812d38ccad0054f0921917f77
      OPERATORS: |
        [
            {"name": "cluster-observability-operator", "source": "coo-catalogsource", "channel": "stable", "install_namespace": "coo", "target_namespaces": "", "operator_group":"coo-og"}
        ]
    test:
    - ref: rhobs-konflux-catalogsource
    - ref: install-operators
    - ref: rhobs-obo-test-harness
    workflow: cucushift-installer-rehearse-gcp-ipi
zz_generated_metadata:
  branch: main
  org: rhobs
  repo: observability-operator
  variant: ocp-4.18-coo
