base_images:
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  observability-operator-test-harness:
    name: observability-operator-test-harness
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.20-openshift-4.14
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    limits:
      memory: 4G
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: stage
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: obs-coo
    product: ocp
    timeout: 3h0m0s
    version: "4.15"
  cron: 0 6 1 8 *
  steps:
    env:
      COO_INDEX_IMAGE: brew.registry.redhat.io/rh-osbs/iib@sha256:4813db400d97fdd67cc63a19dd46afe421a66cfdbb24039ca94ae2c7756373e4
      OPERATORS: |
        [
            {"name": "cluster-observability-operator", "source": "coo-catalogsource", "channel": "stable", "install_namespace": "coo", "target_namespaces": "", "operator_group":"coo-og"}
        ]
    test:
    - ref: rhobs-konflux-catalogsource
    - ref: install-operators
    - ref: rhobs-obo-test-harness
    workflow: generic-claim
zz_generated_metadata:
  branch: main
  org: rhobs
  repo: observability-operator
  variant: ocp-4.15-coo
